# Generated by Django 4.1 on 2022-08-24 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ends at'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='filter_code',
            field=models.ManyToManyField(blank=True, related_name='newsletter', to='app_news.phonecode', verbose_name='code filter'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='filter_tag',
            field=models.ManyToManyField(blank=True, related_name='newsletter', to='app_news.tag', verbose_name='tag filter'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='starts at'),
        ),
    ]
