# Generated by Django 4.1 on 2022-08-24 12:29

import app_news.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_newsletter_ends_at_newsletter_filter_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'newsletter', 'verbose_name_plural': 'newsletters'},
        ),
        migrations.AlterModelOptions(
            name='phonecode',
            options={'verbose_name': 'phone_code', 'verbose_name_plural': 'phone_codes'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.IntegerField(validators=[app_news.validators.validate_phone_number], verbose_name='phone number'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
        migrations.AlterModelTable(
            name='newsletter',
            table='Newsletter',
        ),
        migrations.AlterModelTable(
            name='phonecode',
            table='Phone_code',
        ),
        migrations.AlterModelTable(
            name='status',
            table='Status',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
    ]
