# Generated by Django 4.1 on 2022-08-24 12:36

import app_news.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_alter_client_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[app_news.validators.validate_phone_number], verbose_name='phone number'),
        ),
    ]
