# Generated by Django 4.1 on 2022-08-24 13:06

import app_news.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[app_news.validators.validate_phone_number, django.core.validators.MinLengthValidator(10)], verbose_name='phone number'),
        ),
    ]
