# Generated by Django 4.1 on 2022-08-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_alter_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of sending'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='starts_at',
            field=models.DateTimeField(verbose_name='starts at'),
        ),
    ]
