# Generated by Django 4.1 on 2022-08-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_message_sent_alter_newsletter_starts_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='daily_end',
            field=models.TimeField(blank=True, null=True, verbose_name='daily end'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='daily_start',
            field=models.TimeField(blank=True, null=True, verbose_name='daily start'),
        ),
    ]
